using ClosedXML.Excel;
using ZealEducation.Application.Common.Interfaces;
using ZealEducation.Application.Common.Models;
using ZealEducation.Application.Features.Payments.Queries.GetFinancialReport;
using ZealEducation.Application.Features.Payments.Queries.GetFinancialTransactions;
using ZealEducation.Domain.Enums;

namespace ZealEducation.Infrastructure.Excel;

public class ClosedXmlFinancialReportExcelGenerator : IFinancialReportExcelGenerator
{
    private const string MoneyFormat = "#,##0";
    private const string DateFormat = "yyyy-mm-dd";
    private const string DateTimeFormat = "yyyy-mm-dd hh:mm";
    private static readonly XLColor HeaderFill = XLColor.FromHtml("#1F2937");
    private static readonly XLColor HeaderFont = XLColor.White;
    private static readonly XLColor SectionFill = XLColor.FromHtml("#E5E7EB");

    public byte[] Generate(FinancialReportExcelModel model)
    {
        using var workbook = new XLWorkbook();

        BuildSummarySheet(workbook, model);
        BuildRevenueTrendSheet(workbook, model);
        BuildTransactionsSheet(workbook, model);

        using var stream = new MemoryStream();
        workbook.SaveAs(stream);
        return stream.ToArray();
    }

    private static void BuildSummarySheet(XLWorkbook workbook, FinancialReportExcelModel model)
    {
        var sheet = workbook.Worksheets.Add("Summary");

        // Title
        sheet.Cell(1, 1).Value = "Financial Report";
        sheet.Range(1, 1, 1, 4).Merge();
        sheet.Cell(1, 1).Style.Font.FontSize = 16;
        sheet.Cell(1, 1).Style.Font.Bold = true;

        // Meta info
        sheet.Cell(2, 1).Value = "Generated At";
        sheet.Cell(2, 2).Value = model.GeneratedAt.ToLocalTime();
        sheet.Cell(2, 2).Style.DateFormat.Format = DateTimeFormat;
        sheet.Cell(2, 3).Value = "Generated By";
        sheet.Cell(2, 4).Value = model.GeneratedByStaffName;

        // KPI section
        var row = 4;
        PlainSectionHeader(sheet, row++, "Key Metrics");

        sheet.Cell(row, 1).Value = "Monthly Profit (current month)";
        sheet.Cell(row, 2).Value = model.StatsSummary.MonthlyProfit;
        sheet.Cell(row, 2).Style.NumberFormat.Format = MoneyFormat;
        row++;
        sheet.Cell(row, 1).Value = "Yearly Income (current year)";
        sheet.Cell(row, 2).Value = model.StatsSummary.YearlyIncome;
        sheet.Cell(row, 2).Style.NumberFormat.Format = MoneyFormat;
        row++;
        sheet.Cell(row, 1).Value = "Outstanding Balance";
        sheet.Cell(row, 2).Value = model.StatsSummary.Outstanding;
        sheet.Cell(row, 2).Style.NumberFormat.Format = MoneyFormat;
        row++;
        sheet.Cell(row, 1).Value = "Transaction Count (current year)";
        sheet.Cell(row, 2).Value = model.StatsSummary.TransactionCount;
        row++;

        row++;

        // Payment Status Distribution (uses PaymentStatusRange)
        SectionHeader(sheet, row++, "Payment Status Distribution", model.PaymentStatusRange);
        TableHeader(sheet, row++, "Status", "Fee Count", "Outstanding");
        foreach (var bucket in model.PaymentStatusDistribution)
        {
            sheet.Cell(row, 1).Value = bucket.Status.ToString();
            sheet.Cell(row, 2).Value = bucket.Count;
            sheet.Cell(row, 3).Value = bucket.OutstandingAmount;
            sheet.Cell(row, 3).Style.NumberFormat.Format = MoneyFormat;
            row++;
        }

        row++;

        // Revenue by Fee Type (uses RevenueByFeeTypeRange)
        SectionHeader(sheet, row++, "Revenue by Fee Type", model.RevenueByFeeTypeRange);
        TableHeader(sheet, row++, "Fee Type", "Transactions", "Amount");
        foreach (var bucket in model.RevenueByFeeType)
        {
            sheet.Cell(row, 1).Value = bucket.FeeType.ToString();
            sheet.Cell(row, 2).Value = bucket.Count;
            sheet.Cell(row, 3).Value = bucket.Amount;
            sheet.Cell(row, 3).Style.NumberFormat.Format = MoneyFormat;
            row++;
        }

        row++;

        // Top Courses (uses TopCoursesRange)
        SectionHeader(sheet, row++, "Top Courses by Revenue", model.TopCoursesRange);
        TableHeader(sheet, row++, "Course", "Transactions", "Amount");
        if (model.TopCoursesByRevenue.Count == 0)
        {
            sheet.Cell(row, 1).Value = "No data";
            sheet.Cell(row, 1).Style.Font.Italic = true;
            row++;
        }
        else
        {
            foreach (var course in model.TopCoursesByRevenue)
            {
                sheet.Cell(row, 1).Value = course.CourseTitle;
                sheet.Cell(row, 2).Value = course.TransactionCount;
                sheet.Cell(row, 3).Value = course.Amount;
                sheet.Cell(row, 3).Style.NumberFormat.Format = MoneyFormat;
                row++;
            }
        }

        sheet.Columns().AdjustToContents();
    }

    private static void BuildRevenueTrendSheet(XLWorkbook workbook, FinancialReportExcelModel model)
    {
        var sheet = workbook.Worksheets.Add("Revenue Trend");

        sheet.Cell(1, 1).Value = "Revenue Trend";
        sheet.Cell(1, 1).Style.Font.Bold = true;
        sheet.Cell(1, 1).Style.Font.FontSize = 14;
        sheet.Cell(2, 1).Value = FormatRange(model.RevenueTrendRange);
        sheet.Cell(2, 1).Style.Font.Italic = true;

        TableHeader(sheet, 4, "Date", "Transactions", "Amount");

        var row = 5;
        foreach (var point in model.RevenueTrend)
        {
            sheet.Cell(row, 1).Value = point.Date.ToDateTime(TimeOnly.MinValue);
            sheet.Cell(row, 1).Style.DateFormat.Format = DateFormat;
            sheet.Cell(row, 2).Value = point.Count;
            sheet.Cell(row, 3).Value = point.Amount;
            sheet.Cell(row, 3).Style.NumberFormat.Format = MoneyFormat;
            row++;
        }

        sheet.Columns().AdjustToContents();
    }

    private static void BuildTransactionsSheet(XLWorkbook workbook, FinancialReportExcelModel model)
    {
        var sheet = workbook.Worksheets.Add("Transactions");

        sheet.Cell(1, 1).Value = "Transactions";
        sheet.Cell(1, 1).Style.Font.Bold = true;
        sheet.Cell(1, 1).Style.Font.FontSize = 14;
        sheet.Cell(2, 1).Value = FormatRange(model.TransactionsRange);
        sheet.Cell(2, 1).Style.Font.Italic = true;

        TableHeader(sheet, 4,
            "Receipt No.",
            "Payment Date",
            "Candidate Code",
            "Candidate",
            "Course",
            "Fee Type",
            "Payment Method",
            "Amount",
            "Processed By");

        var row = 5;
        foreach (var tx in model.Transactions)
        {
            sheet.Cell(row, 1).Value = tx.ReceiptNumber;
            sheet.Cell(row, 2).Value = tx.PaymentDate.ToLocalTime();
            sheet.Cell(row, 2).Style.DateFormat.Format = DateTimeFormat;
            sheet.Cell(row, 3).Value = tx.CandidateCode;
            sheet.Cell(row, 4).Value = tx.CandidateFullName;
            sheet.Cell(row, 5).Value = tx.CourseTitle ?? string.Empty;
            sheet.Cell(row, 6).Value = tx.FeeType.ToString();
            sheet.Cell(row, 7).Value = FormatPaymentMethod(tx.PaymentMethod);
            sheet.Cell(row, 8).Value = tx.Amount;
            sheet.Cell(row, 8).Style.NumberFormat.Format = MoneyFormat;
            sheet.Cell(row, 9).Value = tx.ProcessedByStaffName;
            row++;
        }

        if (model.Transactions.Count > 0)
        {
            // Total row
            sheet.Cell(row, 7).Value = "Total";
            sheet.Cell(row, 7).Style.Font.Bold = true;
            sheet.Cell(row, 8).FormulaA1 = $"SUM(H5:H{row - 1})";
            sheet.Cell(row, 8).Style.NumberFormat.Format = MoneyFormat;
            sheet.Cell(row, 8).Style.Font.Bold = true;
            sheet.Cell(row, 8).Style.Fill.BackgroundColor = SectionFill;
        }

        sheet.SheetView.FreezeRows(4);
        sheet.Columns().AdjustToContents();
    }

    private static void SectionHeader(IXLWorksheet sheet, int row, string title, ExcelDateRange range)
    {
        sheet.Cell(row, 1).Value = $"{title}  ({FormatRange(range)})";
        sheet.Range(row, 1, row, 4).Merge();
        sheet.Cell(row, 1).Style.Fill.BackgroundColor = SectionFill;
        sheet.Cell(row, 1).Style.Font.Bold = true;
    }

    private static void PlainSectionHeader(IXLWorksheet sheet, int row, string title)
    {
        sheet.Cell(row, 1).Value = title;
        sheet.Range(row, 1, row, 4).Merge();
        sheet.Cell(row, 1).Style.Fill.BackgroundColor = SectionFill;
        sheet.Cell(row, 1).Style.Font.Bold = true;
    }

    private static void TableHeader(IXLWorksheet sheet, int row, params string[] headers)
    {
        for (var i = 0; i < headers.Length; i++)
        {
            var cell = sheet.Cell(row, i + 1);
            cell.Value = headers[i];
            cell.Style.Fill.BackgroundColor = HeaderFill;
            cell.Style.Font.FontColor = HeaderFont;
            cell.Style.Font.Bold = true;
            cell.Style.Border.OutsideBorder = XLBorderStyleValues.Thin;
        }
    }

    private static string FormatRange(ExcelDateRange range)
        => $"{range.From:yyyy-MM-dd} to {range.To:yyyy-MM-dd}";

    private static string FormatPaymentMethod(PaymentMethod method) => method switch
    {
        PaymentMethod.Cash => "Cash",
        PaymentMethod.BankTransfer => "Bank Transfer",
        _ => method.ToString(),
    };
}
